In [1]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
path = '/Users/sjx/Desktop/SPEC1/data/'
sample0305 = pd.read_csv(path+'reply_sample_0305.csv')
sample0305.head()

,idx,tweet_id,user_id,user_handle,user_party,mentions,replyTo,replyTo_user,candidate_name,candidate_handle,candidate_party,text,urls,context,context_urls
0,0,1056333806666440704,823600613242052610,@DebbyMcG1,democratic,[334245076],1056297474107891712,334245076,George Holding,@GeorgeHolding,republican,@GeorgeHolding Let's call a spade a spade. We...,https://twitter.com/i/web/status/1056333806666...,I am horrified and heartbroken by the vile att...,https://twitter.com/i/web/status/1056297474107...
1,1,1050800554937438210,606803007,@SteveImpParty,democratic,[963480595],1050501836661301252,963480595,Mark Meadows (North Carolina),@RepMarkMeadows,republican,@RepMarkMeadows Oh fuckin stop. You know it's ...,https://twitter.com/i/web/status/1050800554937...,Rod Rosenstein doesn’t show today. Now Fusion'...,https://twitter.com/i/web/status/1050501836661...
2,2,1055177751546748931,816771397825556484,@TenaMarkham1950,democratic,[737719829579345920],1054782611900588033,737719829579345920,Donna Shalala,@DonnaShalala,democratic,@DonnaShalala My sister used to have OBAMACARE...,https://twitter.com/i/web/status/1055177751546...,Thank you President Trump for reminding us tha...,https://twitter.com/i/web/status/1054782611900...
3,3,1055418802207424518,1010666875976650756,@Jaleh93635718,unknown,[2756069574],1054801511631355906,2756069574,Pete Sessions,@SessionsforTX32,republican,@SessionsforTX32 My self calling Washington of...,https://twitter.com/i/web/status/1055418802207...,"When reviewed by the media, Colin is again bus...",https://twitter.com/i/web/status/1054801511631...
4,4,1045075311946158081,31339106,@jona14k,unknown,[76132891],1045074409336315905,76132891,Michael Simpson (Idaho),@CongMikeSimpson,republican,@CongMikeSimpson So I guess you're not watchin...,https://twitter.com/i/web/status/1045075311946...,While Congress certainly does not deserve trop...,https://twitter.com/i/web/status/1045074409336...

In [10]:
cnt = sample0305.groupby('replyTo_user').count().reset_index()
cnt.drop(cnt[cnt['idx'] < 5].index, inplace=True)
cnt.shape

(46, 15)

In [16]:
sample0221 = pd.read_csv(path+'reply_sample_0221.csv')
cnt0221 = sample0221.groupby('replyTo_user').count().reset_index()
cnt0221.drop(cnt0221[cnt0221['tweet_id'] < 5].index, inplace=True)
print(cnt0221.shape)
sample0214 = pd.read_csv(path+'reply_sample_0214.csv')
cnt0214 = sample0214.groupby('replyTo_user').count().reset_index()
cnt0214.drop(cnt0214[cnt0214['tweet_id'] < 5].index, inplace=True)
print(cnt0214.shape)

(0, 10)
(0, 10)

In [18]:
toxic_bal = pd.read_csv(path+'toxic_reply_balance.csv')
toxic_bal.head()

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (12,38) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Unnamed: 0,FLIRTATION,IDENTITY_ATTACK,INFLAMMATORY,INSULT,OBSCENE,PROFANITY,SEVERE_TOXICITY,SEXUALLY_EXPLICIT,THREAT,...,name,party,position,protected,state,url,verified,wikidataID,guessedGender,activityLevel
0,816117,0.382380,0.597905,0.552397,0.895217,0.989232,0.919415,0.729020,0.652246,0.353080,...,Rep. Jim Jordan,republican,house,False,ohio,https://t.co/wd2j7YpRZm,True,NaN,male,4
1,794957,0.384126,0.655396,0.727929,0.824859,0.680344,0.716172,0.702682,0.229307,0.689991,...,Rep. Jim Jordan,republican,house,False,ohio,https://t.co/wd2j7YpRZm,True,NaN,male,4
2,766243,0.582436,0.718969,0.877093,0.765809,0.235341,0.663906,0.707790,0.427944,0.729734,...,Rep. Jim Jordan,republican,house,False,ohio,https://t.co/wd2j7YpRZm,True,NaN,male,4
3,830344,0.246153,0.257582,0.488534,0.797933,0.988132,0.893975,0.719383,0.369486,0.390166,...,Rep. Jim Jordan,republican,house,False,ohio,https://t.co/wd2j7YpRZm,True,NaN,male,4
4,791518,0.129211,0.239942,0.351082,0.976498,0.987413,0.969328,0.747318,0.113550,0.132254,...,Rep. Jim Jordan,republican,house,False,ohio,https://t.co/wd2j7YpRZm,True,NaN,male,4

In [19]:
toxic_bal[toxic_bal['TOXICITY'] < 0.7]

Empty DataFrame
Columns: [Unnamed: 0, FLIRTATION, IDENTITY_ATTACK, INFLAMMATORY, INSULT, OBSCENE, PROFANITY, SEVERE_TOXICITY, SEXUALLY_EXPLICIT, THREAT, TOXICITY, compound, coordinates, deleted, hashtags, tweet_id, isDeleted, media, mentions, neg, neu, place, pos, processed, quote_tweet, replyTo, replyTo_user, sha256, source, text, timestamp, tokens, urls, user, toxic, candidate_name, created_at, description, district, followers_count, friends_count, handle, cand_id, location, name, party, position, protected, state, url, verified, wikidataID, guessedGender, activityLevel]
Index: []

[0 rows x 54 columns]

In [20]:
toxic_bal.columns

Index(['Unnamed: 0', 'FLIRTATION', 'IDENTITY_ATTACK', 'INFLAMMATORY', 'INSULT',
       'OBSCENE', 'PROFANITY', 'SEVERE_TOXICITY', 'SEXUALLY_EXPLICIT',
       'THREAT', 'TOXICITY', 'compound', 'coordinates', 'deleted', 'hashtags',
       'tweet_id', 'isDeleted', 'media', 'mentions', 'neg', 'neu', 'place',
       'pos', 'processed', 'quote_tweet', 'replyTo', 'replyTo_user', 'sha256',
       'source', 'text', 'timestamp', 'tokens', 'urls', 'user', 'toxic',
       'candidate_name', 'created_at', 'description', 'district',
       'followers_count', 'friends_count', 'handle', 'cand_id', 'location',
       'name', 'party', 'position', 'protected', 'state', 'url', 'verified',
       'wikidataID', 'guessedGender', 'activityLevel'],
      dtype='object')

In [62]:
toxic_ready = pd.read_csv(path+'all_toxic_reply_ready.csv')
cnt_ready = toxic_ready.groupby('user_id').count().reset_index()
cnt_ready.drop(cnt_ready[cnt_ready['tweet_id'] < 10].index, inplace=True)
print(cnt_ready.shape)
toxic_ready_repliers = set(cnt_ready['user_id'].tolist())
len(toxic_ready_repliers)

(84, 15)

84

In [48]:
nontoxic_ready = pd.read_csv(path+'all_nontoxic_reply_ready.csv')
print(toxic_ready.shape, nontoxic_ready.shape)

(20582, 15) (87476, 15)

In [49]:
nontoxic_sampled = nontoxic_ready.sample(frac=0.25)

In [63]:
cnt_sampled = nontoxic_sampled.groupby('user_id').count().reset_index()
cnt_sampled.drop(cnt_sampled[cnt_sampled['tweet_id'] < 10].index, inplace=True)
print(cnt_sampled.shape)
nontoxic_sampled_repliers = set(cnt_sampled['user_id'].tolist())
len(nontoxic_sampled_repliers)

(117, 15)

117

In [64]:
combined = toxic_ready_repliers.union(nontoxic_sampled_repliers)
len(combined)

183

In [66]:
sampled = pd.concat([toxic_ready, nontoxic_sampled], ignore_index=True)
cnt_ = sampled.groupby('user_id').count().reset_index()
cnt_.drop(cnt_[cnt_['tweet_id'] < 10].index, inplace=True)
print(cnt_.shape)
sampled_repliers = set(cnt_['user_id'].tolist())
len(sampled_repliers)

(269, 15)

269

In [68]:
all_r = list(sampled_repliers)
all_r

[696459996603813888,
 709055267204235264,
 4873761282,
 549820419,
 711662231843287040,
 715538507767422976,
 726960078859976704,
 728758431297900544,
 729997460916084736,
 731616058495389696,
 741647978096689152,
 748252576265568257,
 808799485165969413,
 310295565,
 825835174382407685,
 543635471,
 829061809135030272,
 864230060177457154,
 1017880119636086794,
 2301628435,
 2218351638,
 957279545652019205,
 1012856766579687429,
 343522845,
 1019360874371244032,
 70060064,
 2807752737,
 2202221609,
 977277439163404288,
 898201537226440705,
 4232562227,
 70068279,
 880568942623903744,
 950875543251111936,
 1403215933,
 21542976,
 4906718786,
 204756038,
 2757657162,
 862685075099484160,
 188621900,
 1953183823,
 21592147,
 3669455956,
 25983061,
 34949718,
 846801440706351104,
 2966712923,
 907688884263407616,
 15976542,
 865621492800774144,
 239023722,
 991774428089520128,
 1018194539813769216,
 1020316972364566528,
 945680647112204288,
 959195357287653376,
 3304203376,
 47144561,
 912816341928890368,
 917985837014568960,
 18964092,
 1260440701,
 940671786957656064,
 982603149742690304,
 1026596403378774016,
 733366950315888640,
 793658020743876608,
 796700265810366464,
 801241407419781120,
 817158650376622080,
 14787206,
 818143654200086529,
 2327100040,
 762506377,
 823706450946101248,
 835553250581614594,
 26571916,
 926086223281688578,
 933783794330619905,
 1004156879101202433,
 825543551186382848,
 966895017296932864,
 862874165581418500,
 2227591831,
 49712794,
 447153824,
 816908447690027008,
 829427709683986432,
 16875684,
 3248034981,
 1034640774338699265,
 16701609,
 272536239,
 2870844593,
 2258064050,
 4349264053,
 238855350,
 1428794042,
 1027433982646841345,
 913851121386577920,
 941807208442028032,
 1861463744,
 918512730025291776,
 1008358184099049472,
 52275398,
 463220423,
 3323513037,
 3958787789,
 977271571680145408,
 1019670010258599936,
 1039975984378912769,
 827195986552385536,
 2427546342,
 552952046,
 1024172301556883456,
 221144816,
 24529137,
 19374322,
 1019943002628796416,
 1033402850980896768,
 1051866135912751104,
 814103288,
 215178490,
 2853499131,
 922079631364317184,
 763490655108734976,
 810535718288236544,
 817928786536701952,
 836645818450993152,
 51788549,
 2646944006,
 3886071558,
 823794567128326145,
 825796725629657089,
 834182887373152257,
 828430723656753154,
 878329612815564800,
 886098346036928513,
 947670287616581633,
 991367690622328833,
 834096988958367747,
 993203891046113282,
 1002673104135643138,
 1002996300416278530,
 1012783050298744835,
 40539925,
 816790149254103040,
 817825066993860608,
 865233740435300356,
 910292386185494528,
 905525182143586309,
 931614483050414080,
 455542556,
 998569456644382721,
 1003961882313744385,
 4262771487,
 976615544890777606,
 1039963309447962629,
 194836261,
 97523501,
 121745711,
 331014449,
 906270633671176192,
 304388915,
 457600819,
 949135191804653568,
 960240942899965952,
 168733495,
 1020086787895508992,
 17539385,
 2425743161,
 1033456367187574784,
 1169579840,
 815310506596691968,
 154727236,
 1385311044,
 926524993655078912,
 989350618614530048,
 355076936,
 85396297,
 1016448397509722112,
 1025169543570718720,
 213697868,
 823528762117537792,
 1019457277881827328,
 1756817240,
 2387351904,
 1948006753,
 3951223649,
 824415983238606848,
 891693542367784960,
 236180325,
 290861413,
 4644755303,
 16966504,
 1021839729971654656,
 1384316268,
 2833302895,
 993955276465192961,
 21576562,
 260417910,
 881738694507479040,
 30759800,
 1343546233,
 38844283,
 1885327740,
 29927805,
 1246181246,
 748857018681847808,
 797940561659523072,
 800018614850088960,
 4591711108,
 68552069,
 597177733,
 743827036305752064,
 784585771923668992,
 814792999381200897,
 815213674239406080,
 1332571531,
 832769112451395585,
 17901453,
 4920129933,
 834079823236562944,
 1017836173345951744,
 3075653521,
 1019689212184891392,
 1043434010754666496,
 824259688300691456,
 838372548156993541,
 373612444,
 826981458946424833,
 766534560,
 1199085984,
 1007298670738407425,
 30999463,
 826524052021874688,
 830583587594342400,
 34943919,
 827907164052275201,
 21651889,
 17847221,
 1056018496671367168,
 898062264,
 894733708053237760,
 1014336132991995904,
 388208060,
 1034636140454662144,
 59676097,
 60519367,
 93457352,
 1009269193,
 414059980,
 122431950,
 451814351,
 526426576,
 1023335376,
 2296729557,
 1558662108,
 382851550,
 336868319,
 875477310887133184,
 2251016167,
 891474352327327744,
 202951147,
 1425911,
 893937284076130304,
 30688766,
 888544924316172289]

In [75]:
dfs = []
for r in all_r:
    try:
        tox = toxic_ready[toxic_ready['user_id']==r].copy()
        tox['from'] = 'tox'
        dfs.append(tox)
    except:
        print(r, 'no toxic replies')
    try:
        nontox = nontoxic_sampled[nontoxic_ready['user_id']==r].copy()
        nontox['from'] = 'nontox'
        dfs.append(nontox)
    except:
        print(r, 'no nontoxic replies')

all_df = pd.concat(dfs, ignore_index=True)
all_df.head()

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:10: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  # Remove the CWD from sys.path while we load stuff.

,Unnamed: 0,tweet_id,user_id,user_handle,user_party,mentions,replyTo,replyTo_user,candidate_name,candidate_handle,candidate_party,text,urls,context,context_urls,from
0,16782,1044937591852863491,696459996603813888,HeatherXoXG,republican,"[3330000369, 37666984]",1044698707655094279,3330000369,Perry Gershon,perrygershon,democratic,@perrygershon If you actually listened To @nik...,https://twitter.com/i/web/status/1044937591852...,Our country deserves more than laughter. \nWe ...,https://twitter.com/i/web/status/1044698707655...,tox
1,16783,1050415681332793345,696459996603813888,HeatherXoXG,republican,"[3330000369, 19608297]",1050413572927438849,3330000369,Perry Gershon,perrygershon,democratic,@perrygershon @HRC You have got to be kidding ...,https://twitter.com/i/web/status/1050415681332...,We have made great strides down the road towar...,https://twitter.com/i/web/status/1050413572927...,tox
2,16784,1054766195474350080,696459996603813888,HeatherXoXG,republican,"[3330000369, 15874918]",1054712699630903301,3330000369,Perry Gershon,perrygershon,democratic,@perrygershon @leezeldin This Ad is Complete C...,https://twitter.com/i/web/status/1054766195474...,Women’s health care is under attack. We see it...,https://twitter.com/i/web/status/1054712699630...,tox
3,16785,1054788551890649089,696459996603813888,HeatherXoXG,republican,[3330000369],1054772685778116613,3330000369,Perry Gershon,perrygershon,democratic,@perrygershon Everything about you is wrong Yo...,https://twitter.com/i/web/status/1054788551890...,This is wrong. \nI know it. You know it. #NY01...,https://twitter.com/i/web/status/1054772685778...,tox
4,16786,1057755057205248000,696459996603813888,HeatherXoXG,republican,"[3330000369, 95275544]",1057686202319552514,3330000369,Perry Gershon,perrygershon,democratic,@perrygershon @indyeastend You and the #Democr...,https://twitter.com/leezeldin/status/105772169...,I am proud to be chosen by @indyeastend as the...,https://twitter.com/i/web/status/1057686202319...,tox

In [76]:
all_df.shape

(4963, 16)

In [77]:
all_cnt = all_df.groupby('user_id').count()
all_cnt['tweet_id'].describe()

count    269.000000
mean      18.449814
std       20.043104
min       10.000000
25%       11.000000
50%       13.000000
75%       20.000000
max      295.000000
Name: tweet_id, dtype: float64

In [96]:
source = all_df[['tweet_id', 'user_id', 'from']].groupby(['user_id', 'from']).count().unstack().reset_index()

In [97]:
source.head()

       user_id tweet_id
from             nontox   tox
0      1425911      7.0   6.0
1     14787206     10.0   2.0
2     15976542     10.0   1.0
3     16701609      9.0   2.0
4     16875684      2.0  13.0

In [98]:
source.columns

MultiIndex(levels=[['tweet_id', 'user_id'], ['nontox', 'tox', '']],
           labels=[[1, 0, 0], [2, 0, 1]],
           names=[None, 'from'])

In [99]:
source.columns = source.columns.droplevel(0)

In [100]:
source.head()

from            nontox   tox
0      1425911     7.0   6.0
1     14787206    10.0   2.0
2     15976542    10.0   1.0
3     16701609     9.0   2.0
4     16875684     2.0  13.0

In [101]:
source[source['tox'] > source['nontox']]

from                       nontox   tox
4                16875684     2.0  13.0
10               19374322     5.0  31.0
15               24529137     1.0  12.0
16               25983061     5.0  18.0
20               30759800     3.0   8.0
21               30999463     1.0  20.0
23               34949718     1.0  10.0
26               47144561     3.0   9.0
29               52275398     1.0  12.0
30               59676097     4.0   8.0
32               68552069    12.0  38.0
36               93457352     7.0  13.0
38              121745711     2.0   9.0
40              154727236     4.0   7.0
41              168733495     5.0   7.0
44              202951147     7.0   8.0
46              213697868     4.0  10.0
47              215178490     2.0   8.0
50              238855350     3.0   7.0
52              260417910     2.0  17.0
53              272536239     7.0  12.0
55              304388915     1.0   9.0
58              336868319     2.0   9.0
60              355076936     4.0   6.0
63              388208060    18.0  24.0
66              451814351     5.0   7.0
67              455542556     6.0  15.0
68              457600819     4.0   6.0
69              463220423     1.0  19.0
71              543635471     8.0  15.0
..                    ...     ...   ...
191    875477310887133184     9.0  21.0
196    888544924316172289     4.0   7.0
197    891474352327327744    17.0  49.0
198    891693542367784960    13.0  23.0
199    893937284076130304     1.0  20.0
201    898201537226440705     5.0   6.0
206    912816341928890368     7.0   9.0
208    917985837014568960     2.0  13.0
209    918512730025291776    12.0  13.0
211    926086223281688578     1.0   9.0
215    940671786957656064     3.0  17.0
216    941807208442028032     2.0  28.0
218    947670287616581633     2.0   9.0
220    950875543251111936     1.0  15.0
222    959195357287653376     1.0   9.0
224    966895017296932864     1.0  11.0
227    977277439163404288     8.0  40.0
232    993203891046113282     5.0   6.0
234    998569456644382721     3.0   9.0
236   1002996300416278530     2.0   8.0
237   1003961882313744385     7.0  13.0
239   1007298670738407425     7.0  10.0
240   1008358184099049472     6.0  14.0
242   1012856766579687429     1.0  11.0
249   1019457277881827328     2.0  11.0
253   1020086787895508992    12.0  17.0
259   1027433982646841345     6.0  12.0
261   1033456367187574784     3.0   9.0
262   1034636140454662144    13.0  53.0
268   1056018496671367168     1.0  10.0

[105 rows x 3 columns]

In [104]:
all_df.drop(['Unnamed: 0', 'user_party', 'mentions', 'candidate_name', 'candidate_party', 'urls', 'context_urls'], axis=1, inplace=True)

In [105]:
all_df.columns

Index(['tweet_id', 'user_id', 'user_handle', 'replyTo', 'replyTo_user',
       'candidate_handle', 'text', 'context', 'from'],
      dtype='object')

In [106]:
all_df.columns = ['reply_id', 'reply_user_id', 'reply_user_name', 'context_id', 'replyTo_user', 'reply_to_name', 'text', 'context', 'from']
all_df.head()

,reply_id,reply_user_id,reply_user_name,context_id,replyTo_user,reply_to_name,text,context,from
0,1044937591852863491,696459996603813888,HeatherXoXG,1044698707655094279,3330000369,perrygershon,@perrygershon If you actually listened To @nik...,Our country deserves more than laughter. \nWe ...,tox
1,1050415681332793345,696459996603813888,HeatherXoXG,1050413572927438849,3330000369,perrygershon,@perrygershon @HRC You have got to be kidding ...,We have made great strides down the road towar...,tox
2,1054766195474350080,696459996603813888,HeatherXoXG,1054712699630903301,3330000369,perrygershon,@perrygershon @leezeldin This Ad is Complete C...,Women’s health care is under attack. We see it...,tox
3,1054788551890649089,696459996603813888,HeatherXoXG,1054772685778116613,3330000369,perrygershon,@perrygershon Everything about you is wrong Yo...,This is wrong. \nI know it. You know it. #NY01...,tox
4,1057755057205248000,696459996603813888,HeatherXoXG,1057686202319552514,3330000369,perrygershon,@perrygershon @indyeastend You and the #Democr...,I am proud to be chosen by @indyeastend as the...,tox

In [107]:
all_df.to_csv('/users/sjx/desktop/spec2/mock.csv', index=False)

In [108]:
all_df.columns

Index(['reply_id', 'reply_user_id', 'reply_user_name', 'context_id',
       'replyTo_user', 'reply_to_name', 'text', 'context', 'from'],
      dtype='object')

In [112]:
all_df[:500].to_csv('/users/sjx/desktop/spec2/mock1.csv', index=False)
all_df[500:1000].to_csv('/users/sjx/desktop/spec2/mock2.csv', index=False)
all_df[1000:1500].to_csv('/users/sjx/desktop/spec2/mock3.csv', index=False)
all_df[1500:2000].to_csv('/users/sjx/desktop/spec2/mock4.csv', index=False)
all_df[2000:2500].to_csv('/users/sjx/desktop/spec2/mock5.csv', index=False)
all_df[2500:3000].to_csv('/users/sjx/desktop/spec2/mock6.csv', index=False)
all_df[3000:3500].to_csv('/users/sjx/desktop/spec2/mock7.csv', index=False)
all_df[3500:4000].to_csv('/users/sjx/desktop/spec2/mock8.csv', index=False)
all_df[4000:4500].to_csv('/users/sjx/desktop/spec2/mock9.csv', index=False)
all_df[4500:].to_csv('/users/sjx/desktop/spec2/mock10.csv', index=False)